<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python list
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.size

<function Tensor.size>

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [10]:
matrix.shape


torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [16]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[0.0573, 0.3818, 0.7059, 0.1013, 0.7883, 0.4374, 0.5168, 0.3344,
          0.9855, 0.6436],
         [0.8966, 0.1520, 0.7538, 0.7800, 0.2240, 0.1522, 0.9402, 0.2758,
          0.3138, 0.5562],
         [0.4839, 0.8289, 0.0797, 0.5855, 0.8866, 0.2518, 0.5912, 0.1390,
          0.9280, 0.9318],
         [0.1905, 0.4471, 0.7015, 0.2586, 0.4755, 0.3459, 0.7213, 0.0260,
          0.2438, 0.5495],
         [0.7483, 0.7321, 0.7226, 0.2136, 0.6741, 0.5353, 0.4710, 0.3940,
          0.7326, 0.7475],
         [0.2045, 0.8317, 0.7694, 0.6596, 0.5365, 0.8705, 0.1315, 0.5640,
          0.0308, 0.7946],
         [0.7172, 0.4598, 0.8819, 0.0036, 0.2451, 0.3589, 0.1104, 0.3210,
          0.9441, 0.2224],
         [0.7385, 0.6956, 0.5882, 0.9260, 0.7787, 0.8823, 0.9130, 0.9010,
          0.9547, 0.9997],
         [0.7695, 0.8466, 0.7432, 0.4516, 0.5140, 0.1741, 0.9821, 0.2355,
          0.0249, 0.0485],
         [0.2003, 0.9833, 0.9916, 0.5282, 0.2304, 0.7196, 0.6940, 0.2169,
          0.8965,

In [17]:
rTensor.ndim



3

In [18]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [19]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
Ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [23]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [27]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [28]:
float_32_tensor.dtype


torch.float32

In [29]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [30]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [31]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [32]:
torch.add(data,10)


tensor([11, 12, 13])

In [33]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [34]:
torch.mul(data,10)

tensor([10, 20, 30])

In [35]:
#Subtract
data-10

tensor([-9, -8, -7])

In [36]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [37]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [38]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [39]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [40]:
# %%time
# value =0
# for i in range(len(data)):
#   value+= data[i] * data[i]
# print(value)

In [41]:
%%time
torch.matmul(data,data)

CPU times: user 413 µs, sys: 107 µs, total: 520 µs
Wall time: 455 µs


tensor(14)

In [42]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[2.5001, 2.5781],
        [2.9990, 3.1829],
        [1.5458, 1.7819],
        [3.2559, 3.2335],
        [1.2162, 1.1898],
        [2.3326, 2.4904],
        [2.2248, 2.6292],
        [3.1497, 3.7389],
        [2.6155, 2.7806],
        [2.4474, 2.3578]])

### Matrix multiplication manually

In [43]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [44]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [45]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [46]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [47]:
tensor_B.T.shape


torch.Size([2, 3])

In [48]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [49]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
x.dtype

torch.int64

In [51]:
x.min()

tensor(0)

In [52]:
torch.min(x)

tensor(0)

In [53]:
x.max()

tensor(90)

In [54]:
torch.max(x)

tensor(90)

In [55]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [56]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
x.sum()

tensor(450)

In [58]:
torch.sum(x)

tensor(450)

In [59]:
x.argmin()

tensor(0)

In [60]:
x.argmax() # Finding the position of Min and Max

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping: Reshaping the input tensor to a defined shape
* View return the view of the input tensor
* Stacking Arranging the object to the top of each other
* Squeezing : remove all the 1 dimentional from the tensor
* Unsqueezing: Adding the one dimentional to the tensor
* Permute: Return the dimension of the view with the permuted sequence

In [61]:
# Lets create the tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x.shape

torch.Size([9])

In [63]:
# to add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [64]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
# using the view
# Changing the x changes the view because the view of the memory shares the same memory as the original tensor shares
z= x.view([3,3])
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
z[:,0]=5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [67]:
#Stack tensor on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##Reshaping the array index

In [68]:
import torch
x= torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [69]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x_reshape.shape

torch.Size([1, 9])

In [71]:
y = torch.tensor([[2,3,4],
                [4,3,6],
                [9,2,4]])
y.shape

torch.Size([3, 3])

In [72]:
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [73]:
x_squeezed = x_reshaped.squeeze()

In [74]:
x_squeezed.shape


torch.Size([9])

In [75]:
print(f" Original data of x was : {x_reshaped}")
print(f" Original dimension of x was : {x_reshaped.shape}")

print(f" After squeezing x becomes: {x_squeezed}")
print(f" After squeezing x becomes: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim =0)

print(f" After Unsqueezing x becomes: {x_unsqueezed}")
print(f" After Unsqueezing x becomes: {x_unsqueezed.shape}")





 Original data of x was : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 Original dimension of x was : torch.Size([1, 9])
 After squeezing x becomes: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
 After squeezing x becomes: torch.Size([9])
 After Unsqueezing x becomes: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 After Unsqueezing x becomes: torch.Size([1, 9])


In [76]:
x_original = torch.rand(size=[230,230,3]) #Height, Width and color manual
x_original.shape

torch.Size([230, 230, 3])

In [77]:
x_permuted = x_original.permute(2,1,0)
x_permuted.shape

torch.Size([3, 230, 230])

In [78]:
x_original[0][0][0]

tensor(0.0278)

In [79]:
x_permuted[0][0][0]

tensor(0.0278)

##Indexing (Searching the item at the particular index)

In [80]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][1]

tensor(2)

In [84]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
x[:,0] #To represent row element

tensor([[1, 2, 3]])

In [86]:
x[:][0][1]

tensor([4, 5, 6])

In [87]:
x[:,:, 1] # To represent column element

tensor([[2, 5, 8]])

In [88]:
x[:,1]

tensor([[4, 5, 6]])

##Pytorch tensor and NumPy
Numpy if the most popular scientific numerical computing library
which is used by pytorch
* torch.from_numpy(ndarray)
* torch.Tensor.numpy()

In [89]:
#Numpy Arry to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
# from tensor to numpy
tensor = torch.ones(7)
Numpy_tensor = tensor.numpy()
tensor, Numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [92]:
tensor = tensor +1
tensor, Numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In [93]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(" The tensor A is :", random_tensor_A)
print(" The tensor B is :", random_tensor_B)
print(" Is tensor A is equals to random B", random_tensor_A==random_tensor_B)


 The tensor A is : tensor([[0.8937, 0.4654, 0.2678, 0.5603],
        [0.0537, 0.6642, 0.3861, 0.0751],
        [0.1445, 0.4223, 0.5901, 0.5587]])
 The tensor B is : tensor([[0.4483, 0.8761, 0.3334, 0.9900],
        [0.2478, 0.8673, 0.3391, 0.5545],
        [0.1610, 0.4025, 0.1212, 0.9586]])
 Is tensor A is equals to random B tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [94]:
RANDOM =42
torch.manual_seed(RANDOM)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)






tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [95]:
!nvedia version

/bin/bash: line 1: nvedia: command not found


In [96]:
!nvidia-smi

Sun Sep 10 04:37:12 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    26W /  70W |    121MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

##Running PyTorch and Tensor object on the GPUs (..and Making Faster Computation)

In [97]:
!nvidia-ima

/bin/bash: line 1: nvidia-ima: command not found


In [98]:
!nvidia-smi

Sun Sep 10 04:42:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    26W /  70W |    121MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#2. Check for the GPU access with PyTorch

In [99]:
import torch
torch.cuda.is_available()

True

In [103]:
#To select GPU or CPU
device = "GPU" if torch.cuda.is_available() else "CPU"
device

'GPU'

In [104]:
# For device Count
torch.cuda.device_count()

1