<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python list
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.size

<function Tensor.size>

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [ ]:
matrix.shape


torch.Size([2, 2])

In [ ]:
matrix.ndim

2

In [ ]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [ ]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[7.9973e-01, 3.1825e-01, 8.5031e-01, 3.2469e-01, 4.0213e-03,
          2.9339e-01, 3.1660e-01, 9.8153e-01, 2.3348e-01, 5.3505e-01],
         [1.4555e-01, 3.3348e-01, 3.3386e-01, 9.7170e-01, 8.8555e-01,
          1.7704e-01, 7.0898e-01, 6.4230e-01, 1.7878e-01, 7.6804e-01],
         [4.2071e-02, 6.3941e-01, 5.2920e-01, 1.5324e-01, 1.2480e-02,
          2.4370e-01, 7.5394e-02, 3.8713e-02, 6.2770e-01, 7.5218e-01],
         [4.1611e-01, 9.2966e-01, 8.4818e-01, 2.9399e-01, 5.6832e-01,
          2.9299e-01, 3.7623e-01, 7.5977e-02, 1.3809e-01, 7.2784e-01],
         [8.5957e-01, 8.8056e-01, 4.9304e-01, 5.4292e-01, 2.0236e-01,
          3.2186e-01, 5.4897e-02, 6.1225e-02, 6.8230e-01, 7.7108e-01],
         [5.1768e-01, 3.8780e-01, 4.4024e-04, 2.8571e-01, 7.4937e-01,
          7.5055e-01, 4.9177e-01, 5.6123e-01, 3.4735e-01, 9.5639e-01],
         [8.4451e-02, 4.1880e-01, 8.6349e-01, 7.5359e-01, 6.8937e-01,
          6.2049e-01, 6.2588e-02, 2.2206e-02, 5.2949e-01, 4.1854e-01],
         [6.1

In [ ]:
rTensor.ndim



3

In [ ]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [ ]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
Ones.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [ ]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [ ]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [ ]:
float_32_tensor.dtype


torch.float32

In [ ]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [ ]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [ ]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [ ]:
torch.add(data,10)


tensor([11, 12, 13])

In [ ]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [ ]:
torch.mul(data,10)

tensor([10, 20, 30])

In [ ]:
#Subtract
data-10

tensor([-9, -8, -7])

In [ ]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [ ]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [ ]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [ ]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [ ]:
%%time
value =0
for i in range(len(data)):
  value+= data[i] * data[i]
print(value)

tensor(14)
CPU times: user 2.05 ms, sys: 0 ns, total: 2.05 ms
Wall time: 1.95 ms


In [ ]:
%%time
torch.matmul(data,data)

CPU times: user 2.32 ms, sys: 27 µs, total: 2.35 ms
Wall time: 2.22 ms


tensor(14)

In [ ]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[2.3417, 3.3719],
        [2.0878, 2.7555],
        [2.0420, 3.2135],
        [2.4353, 3.1207],
        [2.0108, 3.0225],
        [1.5406, 2.9364],
        [2.0200, 2.7282],
        [1.7339, 2.7416],
        [2.4699, 3.0962],
        [2.1384, 4.2255]])

### Matrix multiplication manually

In [15]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [16]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [18]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [20]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [22]:
tensor_B.T.shape


torch.Size([2, 3])

In [23]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [3]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [4]:
x.dtype

torch.int64

In [5]:
x.min()

tensor(0)

In [6]:
torch.min(x)

tensor(0)

In [7]:
x.max()

tensor(90)

In [8]:
torch.max(x)

tensor(90)

In [10]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [11]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

In [ ]:
tensor.sum(x)