<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [8]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [9]:
scalar.ndim

0

In [10]:
#get tensor back as python list
scalar.item()

7

In [11]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.size

<function Tensor.size>

In [14]:
vector.shape

torch.Size([2])

In [15]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [16]:
matrix.shape


torch.Size([2, 2])

In [17]:
matrix.ndim

2

In [18]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [19]:
tensor.ndim

3

In [20]:
tensor.shape

torch.Size([1, 3, 3])

In [21]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [22]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[0.1225, 0.2292, 0.5326, 0.3661, 0.7871, 0.1438, 0.1879, 0.5874,
          0.2546, 0.4269],
         [0.9256, 0.3131, 0.5794, 0.2020, 0.3554, 0.9775, 0.0173, 0.9568,
          0.0466, 0.0333],
         [0.1833, 0.8622, 0.7038, 0.6167, 0.8091, 0.3709, 0.9686, 0.8522,
          0.1281, 0.4688],
         [0.5654, 0.0552, 0.9717, 0.6838, 0.7754, 0.9780, 0.8077, 0.0122,
          0.8566, 0.8447],
         [0.9317, 0.9910, 0.7623, 0.6677, 0.8980, 0.5029, 0.3474, 0.8779,
          0.4231, 0.4461],
         [0.8855, 0.9115, 0.4636, 0.5003, 0.3053, 0.2839, 0.5978, 0.7690,
          0.7774, 0.5163],
         [0.1991, 0.5024, 0.5007, 0.8670, 0.9560, 0.0619, 0.2988, 0.0867,
          0.0654, 0.3459],
         [0.1232, 0.4446, 0.2316, 0.7143, 0.5875, 0.2209, 0.2718, 0.0888,
          0.8097, 0.0089],
         [0.9749, 0.8051, 0.4319, 0.1908, 0.7246, 0.1022, 0.6232, 0.1063,
          0.8755, 0.9563],
         [0.8099, 0.9212, 0.1618, 0.4395, 0.3849, 0.1309, 0.7738, 0.8953,
          0.3184,

In [23]:
rTensor.ndim



3

In [24]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [25]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [26]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
Ones.dtype

torch.float32

In [28]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [29]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [33]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [34]:
float_32_tensor.dtype


torch.float32

In [35]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [36]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [37]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [38]:
torch.add(data,10)


tensor([11, 12, 13])

In [39]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [40]:
torch.mul(data,10)

tensor([10, 20, 30])

In [41]:
#Subtract
data-10

tensor([-9, -8, -7])

In [42]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [43]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [44]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [45]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [72]:
%%time
value =0
for i in range(len(data)):
  value+= data[i] * data[i]
print(value)

TypeError: ignored

In [47]:
%%time
torch.matmul(data,data)

CPU times: user 433 µs, sys: 0 ns, total: 433 µs
Wall time: 378 µs


tensor(14)

In [48]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[1.7187, 2.8978],
        [1.9450, 2.8153],
        [1.7945, 2.6141],
        [1.9847, 3.1831],
        [1.7200, 2.9099],
        [1.4890, 2.2905],
        [2.4272, 3.0321],
        [2.4169, 3.3775],
        [1.6224, 2.1580],
        [2.0177, 3.0789]])

### Matrix multiplication manually

In [49]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [50]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [51]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [52]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [53]:
tensor_B.T.shape


torch.Size([2, 3])

In [54]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [55]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
x.dtype

torch.int64

In [57]:
x.min()

tensor(0)

In [58]:
torch.min(x)

tensor(0)

In [59]:
x.max()

tensor(90)

In [60]:
torch.max(x)

tensor(90)

In [61]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [62]:
x.type(torch.float32).mean()

tensor(45.)

In [63]:
x.sum()

tensor(450)

In [65]:
torch.sum(x)

tensor(450)

In [66]:
x.argmin()

tensor(0)

In [67]:
x.argmax() # Finding the position of Min and Max

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping: Reshaping the input tensor to a defined shape
* View return the view of the input tensor
* Stacking Arranging the object to the top of each other
* Squeezing : remove all the 1 dimentional from the tensor
* Unsqueezing: Adding the one dimentional to the tensor
* Permute: Return the dimension of the view with the permuted sequence

In [78]:
# Lets create the tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
x.shape

torch.Size([9])

In [83]:
# to add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [84]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [91]:
# using the view
# Changing the x changes the view because the view of the memory shares the same memory as the original tensor shares
z= x.view([3,3])
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [94]:
z[:,0]=5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [97]:
#Stack tensor on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])