<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python list
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.size

<function Tensor.size>

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [10]:
matrix.shape


torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [16]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[0.9879, 0.9470, 0.3249, 0.4030, 0.0016, 0.5083, 0.9344, 0.4319,
          0.1880, 0.3301],
         [0.5299, 0.7281, 0.1185, 0.4097, 0.0805, 0.1745, 0.2328, 0.6143,
          0.1827, 0.2176],
         [0.9713, 0.2467, 0.0842, 0.5050, 0.9342, 0.9512, 0.7924, 0.3260,
          0.0988, 0.7423],
         [0.2372, 0.3186, 0.7353, 0.3265, 0.5159, 0.7981, 0.4719, 0.3135,
          0.1170, 0.2589],
         [0.1364, 0.7467, 0.7271, 0.5903, 0.4702, 0.6587, 0.3850, 0.8676,
          0.6687, 0.1404],
         [0.5955, 0.3566, 0.1225, 0.7048, 0.0888, 0.2010, 0.4259, 0.1296,
          0.4349, 0.8234],
         [0.9403, 0.4949, 0.7077, 0.5551, 0.2419, 0.1473, 0.8847, 0.7671,
          0.1670, 0.9333],
         [0.0533, 0.3060, 0.8758, 0.6656, 0.5144, 0.1738, 0.4279, 0.0111,
          0.6458, 0.9566],
         [0.2255, 0.6620, 0.3865, 0.9471, 0.9832, 0.5382, 0.2946, 0.7371,
          0.4579, 0.0998],
         [0.6202, 0.9770, 0.4763, 0.6105, 0.4060, 0.0372, 0.9935, 0.1091,
          0.5482,

In [17]:
rTensor.ndim



3

In [18]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [19]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
Ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [23]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [27]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [28]:
float_32_tensor.dtype


torch.float32

In [29]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [30]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [31]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [32]:
torch.add(data,10)


tensor([11, 12, 13])

In [33]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [34]:
torch.mul(data,10)

tensor([10, 20, 30])

In [35]:
#Subtract
data-10

tensor([-9, -8, -7])

In [36]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [37]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [38]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [39]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [40]:
# %%time
# value =0
# for i in range(len(data)):
#   value+= data[i] * data[i]
# print(value)

In [41]:
%%time
torch.matmul(data,data)

CPU times: user 70 µs, sys: 15 µs, total: 85 µs
Wall time: 89.4 µs


tensor(14)

In [42]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[3.5377, 3.7410],
        [2.9612, 3.1917],
        [2.7197, 2.9398],
        [1.8449, 2.1567],
        [2.6826, 3.8327],
        [2.7490, 3.5898],
        [2.2525, 2.7303],
        [2.3193, 2.6857],
        [2.5191, 2.6803],
        [2.4919, 3.2353]])

### Matrix multiplication manually

In [43]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [44]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [45]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [46]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [47]:
tensor_B.T.shape


torch.Size([2, 3])

In [48]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [49]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
x.dtype

torch.int64

In [51]:
x.min()

tensor(0)

In [52]:
torch.min(x)

tensor(0)

In [53]:
x.max()

tensor(90)

In [54]:
torch.max(x)

tensor(90)

In [55]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [56]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
x.sum()

tensor(450)

In [58]:
torch.sum(x)

tensor(450)

In [59]:
x.argmin()

tensor(0)

In [60]:
x.argmax() # Finding the position of Min and Max

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping: Reshaping the input tensor to a defined shape
* View return the view of the input tensor
* Stacking Arranging the object to the top of each other
* Squeezing : remove all the 1 dimentional from the tensor
* Unsqueezing: Adding the one dimentional to the tensor
* Permute: Return the dimension of the view with the permuted sequence

In [61]:
# Lets create the tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x.shape

torch.Size([9])

In [63]:
# to add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [64]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
# using the view
# Changing the x changes the view because the view of the memory shares the same memory as the original tensor shares
z= x.view([3,3])
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
z[:,0]=5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [67]:
#Stack tensor on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##Reshaping the array index

In [68]:
import torch
x= torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [69]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x_reshape.shape

torch.Size([1, 9])

In [71]:
y = torch.tensor([[2,3,4],
                [4,3,6],
                [9,2,4]])
y.shape

torch.Size([3, 3])

In [72]:
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [73]:
x_squeezed = x_reshaped.squeeze()

In [74]:
x_squeezed.shape


torch.Size([9])

In [75]:
print(f" Original data of x was : {x_reshaped}")
print(f" Original dimension of x was : {x_reshaped.shape}")

print(f" After squeezing x becomes: {x_squeezed}")
print(f" After squeezing x becomes: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim =0)

print(f" After Unsqueezing x becomes: {x_unsqueezed}")
print(f" After Unsqueezing x becomes: {x_unsqueezed.shape}")





 Original data of x was : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 Original dimension of x was : torch.Size([1, 9])
 After squeezing x becomes: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
 After squeezing x becomes: torch.Size([9])
 After Unsqueezing x becomes: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 After Unsqueezing x becomes: torch.Size([1, 9])


In [76]:
x_original = torch.rand(size=[230,230,3]) #Height, Width and color manual
x_original.shape

torch.Size([230, 230, 3])

In [77]:
x_permuted = x_original.permute(2,1,0)
x_permuted.shape

torch.Size([3, 230, 230])

In [78]:
x_original[0][0][0]

tensor(0.0941)

In [79]:
x_permuted[0][0][0]

tensor(0.0941)

##Indexing (Searching the item at the particular index)

In [80]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][1]

tensor(2)

In [84]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
x[:,0] #To represent row element

tensor([[1, 2, 3]])

In [86]:
x[:][0][1]

tensor([4, 5, 6])

In [87]:
x[:,:, 1] # To represent column element

tensor([[2, 5, 8]])

In [88]:
x[:,1]

tensor([[4, 5, 6]])

##Pytorch tensor and NumPy
Numpy if the most popular scientific numerical computing library
which is used by pytorch
* torch.from_numpy(ndarray)
* torch.Tensor.numpy()

In [91]:
#Numpy Arry to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [92]:
array = array +1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [93]:
# from tensor to numpy
tensor = torch.ones(7)
Numpy_tensor = tensor.numpy()
tensor, Numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [96]:
tensor = tensor +1
tensor, Numpy_tensor

(tensor([4., 4., 4., 4., 4., 4., 4.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (Trying to take random out of random)

In [5]:
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(" The tensor A is :", random_tensor_A)
print(" The tensor B is :", random_tensor_B)
print(" Is tensor A is equals to random B", random_tensor_A==random_tensor_B)


 The tensor A is : tensor([[0.4902, 0.8021, 0.0463, 0.5179],
        [0.3383, 0.2594, 0.5517, 0.0721],
        [0.4214, 0.0177, 0.6856, 0.0167]])
 The tensor B is : tensor([[0.5551, 0.6266, 0.6612, 0.5516],
        [0.7174, 0.1614, 0.5741, 0.4297],
        [0.0410, 0.7048, 0.0476, 0.8062]])
 Is tensor A is equals to random B tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [9]:
RANDOM =42
torch.manual_seed(RANDOM)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM)
random_tensor_D = torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)






tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
