<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python list
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.size

<function Tensor.size>

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [10]:
matrix.shape


torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [16]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[0.9920, 0.7057, 0.8982, 0.4676, 0.9980, 0.3196, 0.4849, 0.6493,
          0.4859, 0.5982],
         [0.0071, 0.5098, 0.2505, 0.4081, 0.6306, 0.5311, 0.5792, 0.9447,
          0.8839, 0.2137],
         [0.3976, 0.3085, 0.1275, 0.9518, 0.3279, 0.1143, 0.7630, 0.9833,
          0.4559, 0.9947],
         [0.7755, 0.6975, 0.1599, 0.6919, 0.9274, 0.4844, 0.9717, 0.2367,
          0.2092, 0.1582],
         [0.3858, 0.7030, 0.7635, 0.2008, 0.8893, 0.0399, 0.9547, 0.4346,
          0.6391, 0.3183],
         [0.2336, 0.7762, 0.2119, 0.5219, 0.4698, 0.2416, 0.1963, 0.8263,
          0.0683, 0.7194],
         [0.9442, 0.3511, 0.6119, 0.7038, 0.6894, 0.7310, 0.0718, 0.9066,
          0.5953, 0.4284],
         [0.4896, 0.4799, 0.4930, 0.8614, 0.5116, 0.3870, 0.2871, 0.7391,
          0.7261, 0.0641],
         [0.0216, 0.4908, 0.7257, 0.3183, 0.1771, 0.1205, 0.5392, 0.1037,
          0.7031, 0.0936],
         [0.2818, 0.0295, 0.3832, 0.2477, 0.9995, 0.3362, 0.4243, 0.1821,
          0.6072,

In [17]:
rTensor.ndim



3

In [18]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [19]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
Ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [23]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [27]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [28]:
float_32_tensor.dtype


torch.float32

In [29]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [30]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [31]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [32]:
torch.add(data,10)


tensor([11, 12, 13])

In [33]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [34]:
torch.mul(data,10)

tensor([10, 20, 30])

In [35]:
#Subtract
data-10

tensor([-9, -8, -7])

In [36]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [37]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [38]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [39]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [40]:
# %%time
# value =0
# for i in range(len(data)):
#   value+= data[i] * data[i]
# print(value)

In [41]:
%%time
torch.matmul(data,data)

CPU times: user 40 µs, sys: 10 µs, total: 50 µs
Wall time: 53.6 µs


tensor(14)

In [42]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[1.7168, 2.2033],
        [1.4390, 2.5276],
        [2.2862, 2.3777],
        [1.2818, 2.2505],
        [1.4670, 1.6846],
        [1.4273, 1.8442],
        [1.5599, 1.9170],
        [2.0172, 2.9908],
        [1.6982, 2.7373],
        [1.4771, 2.6717]])

### Matrix multiplication manually

In [43]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [44]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [45]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [46]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [47]:
tensor_B.T.shape


torch.Size([2, 3])

In [48]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [49]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
x.dtype

torch.int64

In [51]:
x.min()

tensor(0)

In [52]:
torch.min(x)

tensor(0)

In [53]:
x.max()

tensor(90)

In [54]:
torch.max(x)

tensor(90)

In [55]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [56]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
x.sum()

tensor(450)

In [58]:
torch.sum(x)

tensor(450)

In [59]:
x.argmin()

tensor(0)

In [60]:
x.argmax() # Finding the position of Min and Max

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping: Reshaping the input tensor to a defined shape
* View return the view of the input tensor
* Stacking Arranging the object to the top of each other
* Squeezing : remove all the 1 dimentional from the tensor
* Unsqueezing: Adding the one dimentional to the tensor
* Permute: Return the dimension of the view with the permuted sequence

In [61]:
# Lets create the tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x.shape

torch.Size([9])

In [63]:
# to add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [64]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
# using the view
# Changing the x changes the view because the view of the memory shares the same memory as the original tensor shares
z= x.view([3,3])
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
z[:,0]=5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [67]:
#Stack tensor on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##Reshaping the array index

In [68]:
import torch
x= torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [69]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x_reshape.shape

torch.Size([1, 9])

In [71]:
y = torch.tensor([[2,3,4],
                [4,3,6],
                [9,2,4]])
y.shape

torch.Size([3, 3])

In [72]:
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [73]:
x_squeezed = x_reshaped.squeeze()

In [74]:
x_squeezed.shape


torch.Size([9])

In [75]:
print(f" Original data of x was : {x_reshaped}")
print(f" Original dimension of x was : {x_reshaped.shape}")

print(f" After squeezing x becomes: {x_squeezed}")
print(f" After squeezing x becomes: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim =0)

print(f" After Unsqueezing x becomes: {x_unsqueezed}")
print(f" After Unsqueezing x becomes: {x_unsqueezed.shape}")





 Original data of x was : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 Original dimension of x was : torch.Size([1, 9])
 After squeezing x becomes: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
 After squeezing x becomes: torch.Size([9])
 After Unsqueezing x becomes: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 After Unsqueezing x becomes: torch.Size([1, 9])


In [76]:
x_original = torch.rand(size=[230,230,3]) #Height, Width and color manual
x_original.shape

torch.Size([230, 230, 3])

In [77]:
x_permuted = x_original.permute(2,1,0)
x_permuted.shape

torch.Size([3, 230, 230])

In [78]:
x_original[0][0][0]

tensor(0.8610)

In [79]:
x_permuted[0][0][0]

tensor(0.8610)

##Indexing (Searching the item at the particular index)

In [80]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][1]

tensor(2)

In [84]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
x[:,0] #To represent row element

tensor([[1, 2, 3]])

In [86]:
x[:][0][1]

tensor([4, 5, 6])

In [87]:
x[:,:, 1] # To represent column element

tensor([[2, 5, 8]])

In [88]:
x[:,1]

tensor([[4, 5, 6]])

##Pytorch tensor and NumPy
Numpy if the most popular scientific numerical computing library
which is used by pytorch
* torch.from_numpy(ndarray)
* torch.Tensor.numpy()