<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [2]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python list
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.size

<function Tensor.size>

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [10]:
matrix.shape


torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [16]:
#Random Tensors
rTensor = torch.rand(1,10,10)
rTensor


tensor([[[9.4686e-01, 9.0824e-01, 9.3008e-03, 4.1878e-01, 5.5479e-01,
          6.0702e-01, 6.5986e-01, 3.4362e-01, 9.2697e-01, 3.9585e-01],
         [4.8391e-01, 6.1933e-02, 2.8658e-03, 4.2417e-02, 2.2754e-01,
          7.8938e-01, 6.6841e-01, 4.6856e-01, 7.6938e-02, 3.6980e-01],
         [9.4423e-01, 7.4838e-01, 4.9803e-01, 3.0469e-01, 3.6176e-01,
          2.7547e-01, 2.5008e-01, 1.0782e-01, 4.5245e-01, 9.6094e-01],
         [3.9515e-01, 4.5756e-01, 6.4319e-01, 2.4482e-01, 5.2437e-01,
          7.7101e-01, 4.0063e-01, 8.4820e-02, 4.1482e-01, 6.8613e-02],
         [2.7692e-01, 4.4402e-02, 2.7013e-01, 1.7534e-01, 6.2009e-01,
          3.6328e-01, 5.7537e-01, 2.8743e-01, 7.5579e-01, 5.1626e-01],
         [8.4764e-02, 1.4179e-01, 9.9220e-01, 5.5875e-01, 7.5311e-01,
          4.8101e-01, 6.7892e-02, 4.1623e-01, 5.0687e-02, 3.8605e-01],
         [8.1571e-01, 7.9008e-01, 4.3792e-01, 9.6109e-01, 4.6003e-04,
          7.9969e-01, 8.9461e-01, 1.6652e-01, 2.8180e-01, 3.5506e-01],
         [8.3

In [17]:
rTensor.ndim



3

In [18]:
#Create a tenson with similar size to an image
rImageSizeTensor = torch.rand(size=(224,224,3))
rImageSizeTensor.shape, rImageSizeTensor.ndim


(torch.Size([224, 224, 3]), 3)

###Zeros and Ones


In [19]:
#Zeros
zeros = torch.zeros(3,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
#Ones
Ones = torch.ones(size=(4,3))
Ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
Ones.dtype

torch.float32

In [22]:
zeros.dtype

torch.float32

###Creatig the Range of Tensors and tensor-like

In [23]:
#Using Tourch arange
range= torch.arange(2,10)
range

tensor([2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#using the arange
one_to_ten = torch.arange(start= 1, end=11, step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#tensor like methods
ten_zeros= torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
ten_ones= torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

###Tensor Datatypes

In [27]:
from IPython.core import display_trap
# Float 32 tensor
float_32_tensor = torch.tensor([4.3,2.0,4.0],
                               dtype=None,
                               device="cuda",
                               requires_grad=False

                               )
float_32_tensor

tensor([4.3000, 2.0000, 4.0000], device='cuda:0')

In [28]:
float_32_tensor.dtype


torch.float32

In [29]:
#float 16
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [30]:
#creating tensor

some_tensor= torch.rand(3,4)

print(" The tensor is some_tensor")
print(f" The data type of tensor is: {some_tensor.dtype}")
print(f" The shape of tensor is: {some_tensor.shape}")
print(f" The device type of tensor is: {some_tensor.device}")


 The tensor is some_tensor
 The data type of tensor is: torch.float32
 The shape of tensor is: torch.Size([3, 4])
 The device type of tensor is: cpu


### Manupulating the Tensor operations
* Addition
* Subtraction
* Multiplication
* Division

In [31]:
#Creating the tensor
data = torch.tensor([1,2,3])


In [32]:
torch.add(data,10)


tensor([11, 12, 13])

In [33]:
# Multiply
data *4

tensor([ 4,  8, 12])

In [34]:
torch.mul(data,10)

tensor([10, 20, 30])

In [35]:
#Subtract
data-10

tensor([-9, -8, -7])

In [36]:
torch.sub(data, 10)

tensor([-9, -8, -7])

### Matrix Multiplication
* Element by element
* Matrix multiply (dot product)

In [37]:
# Multiplying each element
print(f" Equals: {data * data}")

 Equals: tensor([1, 4, 9])


In [38]:
#Multiplying matrix element

matrix = torch.matmul(data,data)
matrix

tensor(14)

In [39]:
#matrix multiplication by hand
1*1 +2*2 + 3*3

14

In [88]:
# %%time
# value =0
# for i in range(len(data)):
#   value+= data[i] * data[i]
# print(value)

In [89]:
%%time
torch.matmul(data,data)

CPU times: user 932 µs, sys: 0 ns, total: 932 µs
Wall time: 940 µs


tensor(14)

In [42]:
#Matrix Multiplications

torch.matmul( torch.rand([10,10]),torch.rand([10,2]))



tensor([[1.8661, 2.4687],
        [2.4167, 2.6546],
        [1.8081, 2.2922],
        [1.6453, 2.3574],
        [1.8637, 2.3780],
        [2.4610, 2.9746],
        [1.4469, 1.7503],
        [2.2180, 3.0344],
        [1.9524, 1.9946],
        [2.2975, 2.3725]])

### Matrix multiplication manually

In [43]:
tensor_A = torch.tensor([[2,3],
                         [3,4],
                         [5,8]])
tensor_B = torch.tensor([[1,9],
                         [8,4],
                         [5,2]])
tensor_A.shape

torch.Size([3, 2])

In [44]:
tensor_B.shape


torch.Size([3, 2])

To fix the shape issue we can use the  **Transpose**

In [45]:
tensor_B


tensor([[1, 9],
        [8, 4],
        [5, 2]])

In [46]:
tensor_B.T # T is used to change the dimention of the the matrix

tensor([[1, 8, 5],
        [9, 4, 2]])

In [47]:
tensor_B.T.shape


torch.Size([2, 3])

In [48]:
torch.mm(tensor_A,tensor_B.T)

tensor([[29, 28, 16],
        [39, 40, 23],
        [77, 72, 41]])

### Finding the min, max, mean sum (Tensor Aggrigation)

In [49]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
x.dtype

torch.int64

In [51]:
x.min()

tensor(0)

In [52]:
torch.min(x)

tensor(0)

In [53]:
x.max()

tensor(90)

In [54]:
torch.max(x)

tensor(90)

In [55]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [56]:
x.type(torch.float32).mean()

tensor(45.)

In [57]:
x.sum()

tensor(450)

In [58]:
torch.sum(x)

tensor(450)

In [59]:
x.argmin()

tensor(0)

In [60]:
x.argmax() # Finding the position of Min and Max

tensor(9)

## Reshaping, Stacking, Squeezing, Unsqueezing
* Reshaping: Reshaping the input tensor to a defined shape
* View return the view of the input tensor
* Stacking Arranging the object to the top of each other
* Squeezing : remove all the 1 dimentional from the tensor
* Unsqueezing: Adding the one dimentional to the tensor
* Permute: Return the dimension of the view with the permuted sequence

In [61]:
# Lets create the tensor
import torch
x = torch.arange(1., 10.)
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [62]:
x.shape

torch.Size([9])

In [63]:
# to add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [64]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [65]:
# using the view
# Changing the x changes the view because the view of the memory shares the same memory as the original tensor shares
z= x.view([3,3])
z,z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [66]:
z[:,0]=5
z,x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [67]:
#Stack tensor on the top of each other
x_stacked= torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

##Reshaping the array index

In [68]:
import torch
x= torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [69]:
x_reshape = x.reshape(1,9)
x_reshape

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
x_reshape.shape

torch.Size([1, 9])

In [71]:
y = torch.tensor([[2,3,4],
                [4,3,6],
                [9,2,4]])
y.shape

torch.Size([3, 3])

In [72]:
x_reshaped

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [73]:
x_squeezed = x_reshaped.squeeze()

In [74]:
x_squeezed.shape


torch.Size([9])

In [75]:
print(f" Original data of x was : {x_reshaped}")
print(f" Original dimension of x was : {x_reshaped.shape}")

print(f" After squeezing x becomes: {x_squeezed}")
print(f" After squeezing x becomes: {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim =0)

print(f" After Unsqueezing x becomes: {x_unsqueezed}")
print(f" After Unsqueezing x becomes: {x_unsqueezed.shape}")





 Original data of x was : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 Original dimension of x was : torch.Size([1, 9])
 After squeezing x becomes: tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
 After squeezing x becomes: torch.Size([9])
 After Unsqueezing x becomes: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
 After Unsqueezing x becomes: torch.Size([1, 9])


In [76]:
x_original = torch.rand(size=[230,230,3]) #Height, Width and color manual
x_original.shape

torch.Size([230, 230, 3])

In [77]:
x_permuted = x_original.permute(2,1,0)
x_permuted.shape

torch.Size([3, 230, 230])

In [78]:
x_original[0][0][0]

tensor(0.9986)

In [79]:
x_permuted[0][0][0]

tensor(0.9986)

##Indexing (Searching the item at the particular index)

In [80]:
import torch
x= torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [82]:
x[0][0]

tensor([1, 2, 3])

In [83]:
x[0][0][1]

tensor(2)

In [84]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [85]:
x[:,0] #To represent row element

tensor([[1, 2, 3]])

In [90]:
x[:][0][1]

tensor([4, 5, 6])

In [91]:
x[:,:, 1] # To represent column element

tensor([[2, 5, 8]])

In [92]:
x[:,1]

tensor([[4, 5, 6]])