<a href="https://colab.research.google.com/github/Shankar034/PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundaments




In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print("Hello this is pytorch fundaments")
print(torch.__version__)



Hello this is pytorch fundaments
2.0.1+cu118


In [ ]:
#scalar
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python list
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.size

<function Tensor.size>

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix = torch.tensor([[7,9],
                      [9,12]])
matrix


tensor([[ 7,  9],
        [ 9, 12]])

In [ ]:
matrix.shape


torch.Size([2, 2])

In [ ]:
matrix.ndim

2

In [20]:
#TENSOR
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [6,7,8]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [21]:
tensor.ndim

3

In [22]:
tensor.shape

torch.Size([1, 3, 3])

In [23]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [6, 7, 8]])

#Random Tensors

In [31]:
#Random Tensors
rTensor = torch.rand(10,10,10)
rTensor


tensor([[[7.9973e-01, 3.1825e-01, 8.5031e-01, 3.2469e-01, 4.0213e-03,
          2.9339e-01, 3.1660e-01, 9.8153e-01, 2.3348e-01, 5.3505e-01],
         [1.4555e-01, 3.3348e-01, 3.3386e-01, 9.7170e-01, 8.8555e-01,
          1.7704e-01, 7.0898e-01, 6.4230e-01, 1.7878e-01, 7.6804e-01],
         [4.2071e-02, 6.3941e-01, 5.2920e-01, 1.5324e-01, 1.2480e-02,
          2.4370e-01, 7.5394e-02, 3.8713e-02, 6.2770e-01, 7.5218e-01],
         [4.1611e-01, 9.2966e-01, 8.4818e-01, 2.9399e-01, 5.6832e-01,
          2.9299e-01, 3.7623e-01, 7.5977e-02, 1.3809e-01, 7.2784e-01],
         [8.5957e-01, 8.8056e-01, 4.9304e-01, 5.4292e-01, 2.0236e-01,
          3.2186e-01, 5.4897e-02, 6.1225e-02, 6.8230e-01, 7.7108e-01],
         [5.1768e-01, 3.8780e-01, 4.4024e-04, 2.8571e-01, 7.4937e-01,
          7.5055e-01, 4.9177e-01, 5.6123e-01, 3.4735e-01, 9.5639e-01],
         [8.4451e-02, 4.1880e-01, 8.6349e-01, 7.5359e-01, 6.8937e-01,
          6.2049e-01, 6.2588e-02, 2.2206e-02, 5.2949e-01, 4.1854e-01],
         [6.1

In [32]:
rTensor.ndim



3